export const soloList = [
    {
      year: 2024,
      order: 1,
      type: "project",
      category_en: "Multidisciplinary performance",
      category_ko: "다원예술공연",
      title_en: "IMAGINE HOME, SWEET HOME",
      title_ko: "이매진 홈, 스위트 홈",
      slug: "/diagram/modal/projects/imagine-home",
      externalUrl: "",
      place_en: "Sapporo Cultural Arts Community Center SCARTS",
      place_ko: "삿포로문화예술교류센터 SCARTS",
      placeUrl: "https://www.sapporo-community-plaza.jp/scarts.php",
      city_en: "Sapporo",
      city_ko: "삿포로",
      country_en: "Japan",
      country_ko: "일본",
    },
    {
        year: 2024,
        order: 2,
        type: "project",
        category_en: "Workshop",
        category_ko: "워크숍",
        title_en: "Baton Touch Dystopia",
        title_ko: "바톤터치 디스토피아",
        slug: "/diagram/modal/projects/baton-touch",
        externalUrl: "",
        place_en: "Amado Art Space",
        place_ko: "아마도예술공간",
        placeUrl: "https://amadoart.org",
        city_en: "Seoul",
        city_ko: "서울",
        country_en: "Korea",
        country_ko: "대한민국",
      },
      {
        year: 2024,
        order: 3,
        type: "project",
        category_en: "Multidisciplinary performance",
        category_ko: "다원예술공연",
        title_en: "MAKE HOME, SWEET HOME",
        title_ko: "메이크 홈, 스위트 홈",
        slug: "/diagram/modal/projects/make-home",
        externalUrl: "",
        place_en: "Doosan Art Center Space111",
        place_ko: "두산아트센터 Space111",
        placeUrl: "https://www.doosanartcenter.com",
        city_en: "Seoul",
        city_ko: "서울",
        country_en: "Korea",
        country_ko: "대한민국",
      },
      {
        year: 2023,
        order: 1,
        type: "project",
        category_en: "Multidisciplinary performance",
        category_ko: "다원예술공연",
        title_en: "PLAY HOME, SWEET HOME",
        title_ko: "플레이 홈, 스위트 홈",
        slug: "/diagram/modal/projects/play-home",
        externalUrl: "",
        place_en: "Post Territory Ujeongguk",
        place_ko: "탈영역우정국",
        placeUrl: "http://ujeongguk.com",
        city_en: "Seoul",
        city_ko: "서울",
        country_en: "Korea",
        country_ko: "대한민국",
      },
      {
        year: 2018,
        order: 1,
        type: "exhibition",
        category_en: "Solo Exhibition",
        category_ko: "개인전",
        title_en: "Warm War",
        title_ko: "따듯한 전쟁",
        slug: "",
        externalUrl: "",
        place_en: "Art Mooak",
        place_ko: "무악파출소",
        placeUrl: "",
        city_en: "Seoul",
        city_ko: "서울",
        country_en: "Korea",
        country_ko: "대한민국",
      },
      {
        year: 2017,
        order: 1,
        type: "exhibition",
        category_en: "Solo Exhibition",
        category_ko: "개인전",
        title_en: "Dead Time Living Labor",
        title_ko: "죽은 시간 산 노동",
        slug: "",
        externalUrl: "",
        place_en: "SPACE UNION",
        place_ko: "스페이스 유니온",
        placeUrl: "",
        city_en: "Seoul",
        city_ko: "서울",
        country_en: "Korea",
        country_ko: "대한민국",
      },
  ];
  
  export const groupList = [
    {
      year: 2024,
      order: 1,
      type: "exhibition",
      category_en: "Group Exhibition",
      category_ko: "단체전",
      title_en: "A Unificd Future: A Held Breath,A Path Unfolding",
      title_ko: "하나의 미래: 머금은 숨, 펼쳐진 길",
      slug: "",
      externalUrl: "https://www.artbava.com/exhibit/하나의-미래-머금은-숨-펼쳐진-길/",
      place_en: "KOREA UNIVERSITY MUSEUM",
      place_ko: "고려대학교 박물관",
      placeUrl: "http://museum.korea.ac.kr/?_gl=1*1bz5spc*_ga*MjA2ODA0MTI4MS4xNzUxNDI4OTE2*_ga_WMMTPV32Y5*czE3NTE0Mjg5MTUkbzEkZzAkdDE3NTE0Mjg5MTUkajYwJGwwJGgw",
      city_en: "Seoul",
      city_ko: "서울",
      country_en: "Korea",
      country_ko: "대한민국",
    },
    {
        year: 2024,
        order: 2,
        type: "exhibition",
        category_en: "Group Exhibition",
        category_ko: "단체전",
        title_en: "The Radiant City, Dark Rapture―Dystopic Images of the Modern City",
        title_ko: "빛나는 도시, 어두운 황홀경―현대 도시의 디스토피아적 이미지들",
        slug: "",
        externalUrl: "https://sema.seoul.go.kr/kr/whatson/exhibition/detail?exNo=1328886",
        place_en: "SeMA Bunker",
        place_ko: "SeMA벙커",
        placeUrl: "https://sema.seoul.go.kr/kr/visit/sema_bunker",
        city_en: "Seoul",
        city_ko: "서울",
        country_en: "Korea",
        country_ko: "대한민국",
      },
      {
        year: 2024,
        order: 3,
        type: "exhibition",
        category_en: "Group Exhibition",
        category_ko: "단체전",
        title_en: "Protect Me From What I Want―Art, the Failed Myth",
        title_ko: "Protect Me From What I Want - 예술, 실패한 신화",
        slug: "",
        externalUrl: "http://www.snumoa.org/exhibitions_view.php?exh_id=179",
        place_en: "Seoul National University Museum of Art",
        place_ko: "서울대미술관",
        placeUrl: "http://www.snumoa.org",
        city_en: "Seoul",
        city_ko: "서울",
        country_en: "Korea",
        country_ko: "대한민국",
      },
      {
        year: 2023,
        order: 1,
        type: "exhibition",
        category_en: "Group Exhibition",
        category_ko: "단체전",
        title_en: "Shelter, City Yeongdeungpo",
        title_ko: "Shelter, 도시 영등포",
        slug: "",
        externalUrl: "https://www.ydpcf.or.kr/artexhibit/view.do?id=363",
        place_en: "LES601",
        place_ko: "LES601 선유점",
        placeUrl: "",
        city_en: "Seoul",
        city_ko: "서울",
        country_en: "Korea",
        country_ko: "대한민국",
      },
      {
        year: 2023,
        order: 2,
        type: "project",
        category_en: "Festival",
        category_ko: "페스티벌",
        title_en: "STREAMS OF WASTE",
        title_ko: "STREAMS OF WASTE",
        slug: "",
        externalUrl: "https://collectivewasteland-6bc26d95705cdc09518.webflow.io/event/bibimbap-news-oct-27",
        place_en: "The Grey Space in the Middle",
        place_ko: "The Grey Space in the Middle",
        placeUrl: "https://thegreyspace.net",
        city_en: "The Hague",
        city_ko: "헤이그",
        country_en: "The Netherlands",
        country_ko: "네덜란드",
      },
      {
        year: 2022,
        order: 1,
        type: "project",
        category_en: "Forum",
        category_ko: "포럼",
        title_en: "Division Images : True or False",
        title_ko: "분단이미지 진품명품",
        slug: "",
        externalUrl: "",
        place_en: "Chuntail Memorial",
        place_ko: "전태일기념관",
        placeUrl: "https://www.taeil.org",
        city_en: "Seoul",
        city_ko: "서울",
        country_en: "Korea",
        country_ko: "대한민국",
      },
      {
        year: 2022,
        order: 2,
        type: "project",
        category_en: "Screening, Sound Performance",
        category_ko: "스크리닝, 사운드 퍼포먼스",
        title_en: "WHISTLE BLOWERS",
        title_ko: "WHISTLE BLOWERS",
        slug: "",
        externalUrl: "",
        place_en: "Hochschule für Bildende Künste–Städelschule",
        place_ko: "슈테델슐레 순수미술아카데미",
        placeUrl: "https://staedelschule.de/de",
        city_en: "Frankfurt am Main",
        city_ko: "프랑크푸르트",
        country_en: "Germany",
        country_ko: "독일",
      },
      {
        year: 2021,
        order: 1,
        type: "exhibition",
        category_en: "Group Exhibition",
        category_ko: "단체전",
        title_en: "The expedition for a cave filled with illusions  and a barrier stitched with patchwork",
        title_ko: "환영으로 채운 굴과 조각보로 기운 장벽 탐사대",
        slug: "",
        externalUrl: "",
        place_en: "Hall 1",
        place_ko: "Hall 1",
        placeUrl: "https://www.instagram.com/hallinfo2020/",
        city_en: "Seoul",
        city_ko: "서울",
        country_en: "Korea",
        country_ko: "대한민국",
      },
      {
        year: 2021,
        order: 2,
        type: "exhibition",
        category_en: "Online Group Exhibition",
        category_ko: "온라인 단체전",
        title_en: "PERFORM COLLECTION SYSTEM",
        title_ko: "PERFORM COLLECTION SYSTEM",
        slug: "",
        externalUrl: "https://ebxxrum.gitlab.io/invitation-html.gitlab.io/",
        place_en: "performplace.org",
        place_ko: "performplace.org",
        placeUrl: "https://ebxxrum.gitlab.io/invitation-html.gitlab.io/",
        city_en: "Online",
        city_ko: "온라인",
        country_en: "",
        country_ko: "",
      },
      {
        year: 2021,
        order: 3,
        type: "exhibition",
        category_en: "Group Exhibition",
        category_ko: "단체전",
        title_en: "From Amazon to Olympic",
        title_ko: "From Amazon to Olympic",
        slug: "",
        externalUrl: "https://barimart.wordpress.com/2021/12/02/from-amazon-to-olympic/",
        place_en: "Barim, Tenjinyama Art Studio",
        place_ko: "바림, 텐진야마 아트 스튜디오",
        placeUrl: "https://tenjinyamastudio.jp",
        city_en: "Gwangju, Sapporo",
        city_ko: "광주, 삿포로",
        country_en: "Korea, Japan",
        country_ko: "한국, 일본",
      },
      {
        year: 2021,
        order: 4,
        type: "exhibition",
        category_en: "Group Exhibition",
        category_ko: "단체전",
        title_en: "소소한 이야기의 숲 : 대림",
        title_ko: "소소한 이야기의 숲 : 대림",
        slug: "",
        externalUrl: "https://ydpcf.or.kr/postview.do?bid=1&pid=639",
        place_en: "The Daerim-dong area",
        place_ko: "대림동 일대",
        placeUrl: "",
        city_en: "Seoul",
        city_ko: "서울",
        country_en: "Korea",
        country_ko: "한국",
      },
      {
        year: 2021,
        order: 5,
        type: "exhibition",
        category_en: "Online Group Exhibition",
        category_ko: "온라인 단체전",
        title_en: "the 17th International Architecture Exhibition Future School",
        title_ko: "제17회 베니스비엔날레 국제건축전 미래학교 : 상상된 디아스포라",
        slug: "",
        externalUrl: "https://www.arko.or.kr/pavilion/20pavilion/index.html",
        place_en: "Future School Online",
        place_ko: "미래학교 온라인",
        placeUrl: "",
        city_en: "Online",
        city_ko: "온라인",
        country_en: "",
        country_ko: "",
      },
      {
        year: 2021,
        order: 6,
        type: "project",
        category_en: "Presentation",
        category_ko: "프레젠테이션",
        title_en: "White Letters",
        title_ko: "White Letters",
        slug: "",
        externalUrl: "https://barimart.wordpress.com/2021/03/04/wlpresentation/",
        place_en: "Barim, Tenjinyama Art Studio",
        place_ko: "바림, 텐진야마 아트 스튜디오",
        placeUrl: "",
        city_en: "Online",
        city_ko: "온라인",
        country_en: "",
        country_ko: "",
      },
      {
        year: 2020,
        order: 1,
        type: "exhibition",
        category_en: "Group Exhibition",
        category_ko: "단체전",
        title_en: "Busan International Video Art Festival: Vector of Oppression",
        title_ko: "제14회 부산국제비디오아트페스티발: 억압의 벡터",
        slug: "",
        externalUrl: "https://www.videoartbusan.com/주제-topic-1",
        place_en: "SPACE HEEM",
        place_ko: "공간힘",
        placeUrl: "https://spaceheem.com",
        city_en: "Busan",
        city_ko: "부산",
        country_en: "Kroea",
        country_ko: "대한민국",
      },
      {
        year: 2020,
        order: 2,
        type: "exhibition",
        category_en: "Group Exhibition",
        category_ko: "단체전",
        title_en: "Collective Chungjeongro: Cave Simulation",
        title_ko: "콜렉티브 충정로:동굴 시뮬레이션",
        slug: "",
        externalUrl: "http://www.sapy.kr/CS_Program",
        place_en: "SAPY",
        place_ko: "청년예술청",
        placeUrl: "http://www.sapy.kr/MAIN",
        city_en: "Seoul",
        city_ko: "서울",
        country_en: "Kroea",
        country_ko: "대한민국",
      },
      {
        year: 2020,
        order: 3,
        type: "exhibition",
        category_en: "Group Exhibition",
        category_ko: "단체전",
        title_en: "Alone-Together",
        title_ko: "따로-같이",
        slug: "",
        externalUrl: "https://www.taeil.org/exhibition/detail?id=14",
        place_en: "Chuntaeil Memorial",
        place_ko: "전태일기념관",
        placeUrl: "https://www.taeil.org",
        city_en: "Seoul",
        city_ko: "서울",
        country_en: "Kroea",
        country_ko: "대한민국",
      },
      {
        year: 2019,
        order: 1,
        type: "exhibition",
        category_en: "Group Exhibition",
        category_ko: "단체전",
        title_en: "Nothing to My Name",
        title_ko: "일무소유",
        slug: "",
        externalUrl: "",
        place_en: "Seoul Art Space Mullae M30",
        place_ko: "문래예술공장 M30",
        placeUrl: "",
        city_en: "Seoul",
        city_ko: "서울",
        country_en: "Kroea",
        country_ko: "대한민국",
      },
      {
        year: 2019,
        order: 2,
        type: "exhibition",
        category_en: "Group Exhibition",
        category_ko: "단체전",
        title_en: "Running Room",
        title_ko: "러닝룸:간병인, 거리입양, 구제역, 국경, 기시감, 다운사이징, 만주국, 오로첸, 전이, 카메라, 풍경, 흑룡강",
        slug: "",
        externalUrl: "",
        place_en: "Gallery Azit",
        place_ko: "사진문화공간 아지트",
        placeUrl: "",
        city_en: "Seoul",
        city_ko: "서울",
        country_en: "Kroea",
        country_ko: "대한민국",
      },
      {
        year: 2019,
        order: 3,
        type: "project",
        category_en: "Project",
        category_ko: "프로젝트",
        title_en: "Beyond Lamb Skewers",
        title_ko: "대림동엔 양꼬치 먹으러 가는 줄만 알았다",
        slug: "",
        externalUrl: "",
        place_en: "999 Live Bar",
        place_ko: "999라이브바",
        placeUrl: "",
        city_en: "Seoul",
        city_ko: "서울",
        country_en: "Kroea",
        country_ko: "대한민국",
      },
      {
        year: 2019,
        order: 4,
        type: "project",
        category_en: "Screening",
        category_ko: "스크리닝",
        title_en: "10th Obviously Video : 3 to 5",
        title_ko: "안봐도 비디오 10회 : 3to 5",
        slug: "",
        externalUrl: "https://artlecture.com/project/3411",
        place_en: "oh!zemidong",
        place_ko: "충무로영상센터 오!재미동",
        placeUrl: "",
        city_en: "Seoul",
        city_ko: "서울",
        country_en: "Kroea",
        country_ko: "대한민국",
      },
      {
        year: 2019,
        order: 5,
        type: "exhibition",
        category_en: "Group Exhibition",
        category_ko: "단체전",
        title_en: "Sida’s Dream",
        title_ko: "시다의 꿈",
        slug: "",
        externalUrl: "https://www.taeil.org/exhibition/detail?id=8",
        place_en: "Chuntaeil Memorial",
        place_ko: "전태일기념관",
        placeUrl: "https://www.taeil.org",
        city_en: "Seoul",
        city_ko: "서울",
        country_en: "Kroea",
        country_ko: "대한민국",
      },
    
  ];